//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebClient.ImageService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Word", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Word : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WnidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CategoryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PopularityField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Wnid {
            get {
                return this.WnidField;
            }
            set {
                if ((object.ReferenceEquals(this.WnidField, value) != true)) {
                    this.WnidField = value;
                    this.RaisePropertyChanged("Wnid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Category {
            get {
                return this.CategoryField;
            }
            set {
                if ((object.ReferenceEquals(this.CategoryField, value) != true)) {
                    this.CategoryField = value;
                    this.RaisePropertyChanged("Category");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Count {
            get {
                return this.CountField;
            }
            set {
                if ((object.ReferenceEquals(this.CountField, value) != true)) {
                    this.CountField = value;
                    this.RaisePropertyChanged("Count");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Popularity {
            get {
                return this.PopularityField;
            }
            set {
                if ((object.ReferenceEquals(this.PopularityField, value) != true)) {
                    this.PopularityField = value;
                    this.RaisePropertyChanged("Popularity");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ImageService.ImageWebServiceSoap")]
    public interface ImageWebServiceSoap {
        
        // CODEGEN: Контракт генерации сообщений с именем line из пространства имен http://tempuri.org/ не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FindWord", ReplyAction="*")]
        WebClient.ImageService.FindWordResponse FindWord(WebClient.ImageService.FindWordRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FindWord", ReplyAction="*")]
        System.Threading.Tasks.Task<WebClient.ImageService.FindWordResponse> FindWordAsync(WebClient.ImageService.FindWordRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FindWordRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FindWord", Namespace="http://tempuri.org/", Order=0)]
        public WebClient.ImageService.FindWordRequestBody Body;
        
        public FindWordRequest() {
        }
        
        public FindWordRequest(WebClient.ImageService.FindWordRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class FindWordRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string line;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string key;
        
        public FindWordRequestBody() {
        }
        
        public FindWordRequestBody(string line, string key) {
            this.line = line;
            this.key = key;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FindWordResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FindWordResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebClient.ImageService.FindWordResponseBody Body;
        
        public FindWordResponse() {
        }
        
        public FindWordResponse(WebClient.ImageService.FindWordResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class FindWordResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WebClient.ImageService.Word FindWordResult;
        
        public FindWordResponseBody() {
        }
        
        public FindWordResponseBody(WebClient.ImageService.Word FindWordResult) {
            this.FindWordResult = FindWordResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ImageWebServiceSoapChannel : WebClient.ImageService.ImageWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ImageWebServiceSoapClient : System.ServiceModel.ClientBase<WebClient.ImageService.ImageWebServiceSoap>, WebClient.ImageService.ImageWebServiceSoap {
        
        public ImageWebServiceSoapClient() {
        }
        
        public ImageWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ImageWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ImageWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ImageWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebClient.ImageService.FindWordResponse WebClient.ImageService.ImageWebServiceSoap.FindWord(WebClient.ImageService.FindWordRequest request) {
            return base.Channel.FindWord(request);
        }
        
        public WebClient.ImageService.Word FindWord(string line, string key) {
            WebClient.ImageService.FindWordRequest inValue = new WebClient.ImageService.FindWordRequest();
            inValue.Body = new WebClient.ImageService.FindWordRequestBody();
            inValue.Body.line = line;
            inValue.Body.key = key;
            WebClient.ImageService.FindWordResponse retVal = ((WebClient.ImageService.ImageWebServiceSoap)(this)).FindWord(inValue);
            return retVal.Body.FindWordResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebClient.ImageService.FindWordResponse> WebClient.ImageService.ImageWebServiceSoap.FindWordAsync(WebClient.ImageService.FindWordRequest request) {
            return base.Channel.FindWordAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebClient.ImageService.FindWordResponse> FindWordAsync(string line, string key) {
            WebClient.ImageService.FindWordRequest inValue = new WebClient.ImageService.FindWordRequest();
            inValue.Body = new WebClient.ImageService.FindWordRequestBody();
            inValue.Body.line = line;
            inValue.Body.key = key;
            return ((WebClient.ImageService.ImageWebServiceSoap)(this)).FindWordAsync(inValue);
        }
    }
}
